#ifndef NETWORK_CONTROL_MESSAGE_PROTOCOL_H
#define NETWORK_CONTROL_MESSAGE_PROTOCOL_H


#include "network.h"


/**
 * NCMP Time Exceeded is generated by any host or router to inform the source of a
 * discarded datagram due to the hop count field reaching zero.
 *
 * The code must be 0x00. This message don't have any data.
 */
#define NCMP_TIME_EXCEED                0x0B


/**
 * NCMP Adoption Announcement is generated by any host conecting to the network through
 * zeroconf process. In this case, the host need a another host to be your parent.
 *
 * The code must be 0x00. This message don't have any data.
 */
#define NCMP_ADOPTION_ANNOUNCEMENT      0x2A


/**
 * NCMP Adoption Request is generated by any host in response to a previous Adoption
 * Announcement. Any host that can comunicate with the router (root node of the network)
 * can request an adoption. If a host wihtout comunication with the router receive this
 * message, it must ignore.
 *
 * The code must be 0x00. The data field is assembled as follows: the first 8 bits must
 * contain the current number of the children of the current host; the next 16 bits must contain
 * the network address that can be used by the adopted host, if it accept; the next 8 bits
 * must contain how long (in seconds) the current host will reserve that address to the
 * host (after this time the current host will not accept the adoption anymore).
 */
#define NCMP_ADOPTION_REQUEST           0x2B


/**
 * NCMP Adoption Replay is generated by any host that accepted an Adoption Request from
 * another one.
 *
 * The code must be 0x00. The data field is assembled as follows: the first
 */
#define NCMP_ADOPTION_REPLY             0x2A


/**
 * NCMP Echo Request is used to test the reachability of a host and to measure the round-trip
 * time for messages sent between two hosts.
 *
 * The code must be 0x00. The data field is assembled as follows: the first 8 bits must contain
 * an unique ID of the session; the next 8 bits must contain the a sequence number; the last
 * 16 bits must be ignored.
 */
#define NMCP_ECHO_REQUEST               0x08

/**
 * NCMP Echo Reply is generated as response to a Echo Request.
 *
 * The code must be 0x00. The data field is assembled as follows: the first 8 bits must contain
 * an unique ID of the session; the next 8 bits must contain the a sequence number; the last
 * 16 bits must be ignored.
 */
#define NMCP_ECHO_REPLAY                0x00


typedef struct
{

	uint8_t type;

	uint8_t code;

	uint32_t data;

} ncmp_packet_t;


void ncmp_send(
	network_context_t *context,
	uint16_t destination,
	uint8_t type,
	uint8_t code,
	uint32_t data );


#endif  // NETWORK_CONTROL_MESSAGE_PROTOCOL_H
